version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./var/${MYSQL_DBNAME}.sql:/docker-entrypoint-initdb.d/${MYSQL_DBNAME}.sql:z
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
volumes:
  mysql_data: { }
